# Generated by Django 3.2.8 on 2021-11-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20211118_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Name', max_length=60),
        ),
    ]
