# Generated by Django 3.2.8 on 2021-11-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_hero_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='companyAge',
            field=models.CharField(default='1 Year', max_length=999),
        ),
        migrations.AddField(
            model_name='hero',
            name='companyCameras',
            field=models.CharField(default='17', max_length=999),
        ),
        migrations.AddField(
            model_name='hero',
            name='companySqft',
            field=models.CharField(default='6,000', max_length=999999999),
        ),
        migrations.AddField(
            model_name='hero',
            name='companySummary',
            field=models.CharField(default='May Realities sells Computer Vision software.', max_length=120),
        ),
        migrations.AddField(
            model_name='hero',
            name='email',
            field=models.CharField(default='email@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='password',
            field=models.CharField(default='password', max_length=999),
        ),
    ]
