# Generated by Django 3.2.8 on 2021-11-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20211118_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='companyName',
            field=models.CharField(default='May Realities, Inc.', max_length=999),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Jane Doe', max_length=60),
        ),
    ]
