# Generated by Django 3.2.8 on 2021-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeDetectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOW', models.CharField(max_length=20)),
                ('CD', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LostInventoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOW', models.CharField(max_length=20)),
                ('LI', models.CharField(max_length=1000)),
            ],
        ),
    ]
