# Generated by Django 3.2.8 on 2021-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20211119_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='username',
            field=models.CharField(default='Username', max_length=60),
        ),
    ]
