# Generated by Django 3.2.8 on 2021-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_hero_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=100)),
            ],
        ),
    ]
