# Generated by Django 3.2.8 on 2021-11-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_rename_li_crimedetectiondata_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetectiondata',
            name='CS',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LI',
            field=models.CharField(max_length=100),
        ),
    ]
