# Generated by Django 3.2.8 on 2021-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20211126_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(default='Notification', max_length=9999),
        ),
    ]
