# Generated by Django 3.2.8 on 2021-11-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_notification_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostinventorydata',
            name='LI',
        ),
    ]
