# Generated by Django 3.2.8 on 2021-11-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20211127_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimedetectiondata',
            name='CS',
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSF',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSM',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSST',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSSU',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CST',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSTH',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='crimedetectiondata',
            name='CSW',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LIF',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LIM',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LISA',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LISU',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LIT',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LITH',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AlterField(
            model_name='lostinventorydata',
            name='LIW',
            field=models.CharField(default='0', max_length=100000),
        ),
    ]
