# Generated by Django 3.2.8 on 2021-11-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20211127_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='premium',
            field=models.IntegerField(default=0),
        ),
    ]
