# Generated by Django 3.2.8 on 2021-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_hero_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='hero',
            name='firstName',
            field=models.CharField(default='Jane', max_length=60),
        ),
    ]
