# Generated by Django 3.2.8 on 2021-12-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_cameraapi_cameraname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraapi',
            name='cameraIndex',
            field=models.IntegerField(default=1),
        ),
    ]
