# Generated by Django 3.2.8 on 2021-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_cameraapi_cameraindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Message', max_length=200)),
            ],
        ),
    ]
